//! Turn the built dashboard into a Rust table the binary carries.
//!
//! The dashboard is a Vite build, and Rust must not need Node to compile. So
//! this reads whatever is in `ui/dist` and writes an array of
//! `(path, content_type, bytes)`; when there is no `dist`, it writes an empty
//! one and the crate reports honestly that no dashboard was bundled. A
//! developer with no Node toolchain gets a working `ctxc`, and a release build
//! runs `npm run build` first.
//!
//! Files are embedded with `include_bytes!` rather than pasted in as literals,
//! so the compiler reads each one directly and rebuilds when it changes.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let dist = manifest.join("ui").join("dist");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=ui/dist");

    let mut files = Vec::new();
    collect(&dist, &dist, &mut files);
    files.sort();

    let mut generated = String::new();
    generated.push_str(
        "// Generated by build.rs. Do not edit.\n\
         pub static ASSETS: &[Asset] = &[\n",
    );

    for (route, absolute) in &files {
        // Paths go into the generated source as literals, so a backslash from
        // Windows has to survive as a backslash rather than start an escape.
        let escaped = absolute.display().to_string().replace('\\', "\\\\");
        let content_type = content_type(route);
        writeln!(
            generated,
            "    Asset {{ path: {route:?}, content_type: {content_type:?}, \
             bytes: include_bytes!(\"{escaped}\") }},"
        )
        .expect("writing to a String cannot fail");
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this")).join("assets.rs");
    std::fs::write(&out, generated).expect("write the generated asset table");
}

/// Walk `directory`, recording each file under the route it should answer.
fn collect(root: &Path, directory: &Path, files: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(directory) else {
        // No dist: a source checkout that has not built the UI. Not an error.
        return;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, files);
            continue;
        }

        let Ok(relative) = path.strip_prefix(root) else {
            continue;
        };
        // Routes are URL paths, which use forward slashes on every platform.
        let route = relative
            .components()
            .map(|part| part.as_os_str().to_string_lossy().into_owned())
            .collect::<Vec<String>>()
            .join("/");

        println!("cargo:rerun-if-changed={}", path.display());
        files.push((route, path));
    }
}

/// The content type a route should be served as.
///
/// Deliberately a short list: these are the only kinds of file a Vite build
/// produces, and guessing at anything else would be worse than saying
/// `application/octet-stream`.
fn content_type(route: &str) -> &'static str {
    match route.rsplit('.').next().unwrap_or_default() {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" => "application/json",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "webp" => "image/webp",
        "ico" => "image/x-icon",
        "woff2" => "font/woff2",
        "woff" => "font/woff",
        "map" => "application/json",
        "txt" => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}
